version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: php8
    depends_on:
      - bd
    volumes:
      - ./app:/var/www/html
    ports:
      - 9000:80
  bd:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 6034:3306
  
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: adminbd
    ports:
        - '9001:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - bd