version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: php8
    depends_on:
      - project
    volumes:
      - ./app:/var/www/html
    ports:
      - 9000:80
  project:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: project
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - 6034:3306
  
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    ports:
        - '9001:80'
    restart: always
    environment:
        PMA_HOST: mysql8
    depends_on:
        - project